### ISSUE TITLE
Crafter's Remember items button locks inventory (reopen #97)

### ISSUE THREAD

**Issue by LuciusV** [McJtyMods/RFToolsUtility#121] opened 2022-01-17 14:31 UTC
Hi!
This issue
https://github.com/McJtyMods/RFToolsUtility/issues/97
still persists in Rftools Utility 1.16-3.1.8 (modpack FTB-Endeavour) and 1.16-3.1.9 (upgraded Rftools Utility to last version - to no effect)
 Has the fix you mentioned not been released yet?

**Comment by McJty** [comment] 2022-01-17 14:34
Hmm. I need a better way to reproduce this because I can't

**Comment by LuciusV** [comment] 2022-01-17 14:36
Only  1x9 inventory hotbar can be used to place items, but 3x9 inventory is not
I will try make clean Minecraft instance and reproduce with as few mods as possible

**Comment by McJty** [comment] 2022-01-28 09:48
I could finally reproduce this. I will fix

**Comment by McJty** [comment] 2022-01-28 09:55
Will be fixed next release (both 1.16 and 1.18)

**Closed as completed by McJty** 2022-01-28 09:55 UTC

**Comment by LuciusV** [comment] 2022-01-28 13:34
Thank you so much
